#!/bin/bash

# Script to check environment variables on Render
# You'll need to manually get your Render API key from: https://dashboard.render.com/u/settings#api-keys

echo "==================================="
echo "Render Environment Variables Check"
echo "==================================="
echo ""
echo "Service: muralla-backend (srv-d31r2pndiees7386lklg)"
echo ""
echo "To check your environment variables, please:"
echo ""
echo "1. Go to: https://dashboard.render.com/web/srv-d31r2pndiees7386lklg"
echo "2. Click on 'Environment' in the left sidebar"
echo "3. Compare the variables there with the required list below:"
echo ""
echo "REQUIRED ENVIRONMENT VARIABLES:"
echo "-------------------------------"
echo "✓ DATABASE_URL"
echo "✓ JWT_SECRET"
echo "✓ GOOGLE_TASKS_ENABLED"
echo "✓ GOOGLE_CLIENT_ID"
echo "✓ GOOGLE_CLIENT_SECRET"
echo "✓ GOOGLE_REDIRECT_URI"
echo "✓ GOOGLE_CHAT_CLIENT_EMAIL"
echo "✓ GOOGLE_CHAT_PRIVATE_KEY"
echo "✓ GOOGLE_CHAT_ADMIN_EMAIL"
echo "✓ OPENFACTURA_API_KEY"
echo "✓ OPENFACTURA_API_KEY_MURALLA"
echo "✓ OPENFACTURA_API_KEY_MURALLITA"
echo "✓ GEMINI_API_KEY"
echo "✓ OPENAI_API_KEY"
echo "✓ GOOGLE_CUSTOM_SEARCH_API_KEY"
echo "✓ GOOGLE_SEARCH_ENGINE_ID"
echo "✓ CLOUDINARY_CLOUD_NAME"
echo "✓ CLOUDINARY_API_KEY"
echo "✓ CLOUDINARY_API_SECRET"
echo "✓ SEED_SECRET"
echo "✓ CRON_SECRET"
echo ""
echo "OR use the API directly:"
echo "curl -H 'Authorization: Bearer YOUR_RENDER_API_KEY' \\"
echo "  https://api.render.com/v1/services/srv-d31r2pndiees7386lklg/env-vars"
echo ""
echo "Get your API key from: https://dashboard.render.com/u/settings#api-keys"

