-- Disable Row Level Security (RLS) for Development
-- This allows Prisma to query all tables without authentication issues
-- WARNING: Only use this in development! Re-enable RLS for production.

-- Disable RLS on all tables
ALTER TABLE IF EXISTS staff DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tenants DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS task_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS task_comments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS task_dependencies DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS products DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS inventory_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS transaction_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS contact_type_configs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS contact_field_configs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS staff_contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payment_accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS expense_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS expense_statuses DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tax_documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS purchase_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS purchase_order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS shifts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS attendances DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS pto_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payroll_runs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS employee_reimbursements DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS api_keys DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS modifier_groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS product_modifiers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS transaction_item_modifiers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS product_variants DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS recipes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS recipe_ingredients DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS production_batches DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ingredient_consumptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS product_movements DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS staff_products DISABLE ROW LEVEL SECURITY;

-- Optional: Drop all existing policies (if any)
-- This ensures no policies interfere with queries
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (
        SELECT schemaname, tablename, policyname
        FROM pg_policies
        WHERE schemaname = 'public'
    ) LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I.%I',
            r.policyname, r.schemaname, r.tablename);
    END LOOP;
END $$;

-- Verify RLS is disabled
SELECT
    schemaname,
    tablename,
    rowsecurity as "RLS Enabled"
FROM pg_tables
WHERE schemaname = 'public'
ORDER BY tablename;
